crud/crud/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

crud/employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employeess"  
class Employee1(models.Model):  
    eid     = models.CharField(max_length=20)  
    ename   = models.CharField(max_length=100)  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee1"  

crud/employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

crud/employee/views.py
from django.shortcuts import render, redirect  
from employee.forms import EmployeeForm  
from employee.models import Employee  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

crud/employee/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title> 
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <table>      
    <tr><th colspan="2"><h3>Update Details</h3></th></tr>  
        <tr><td> Employee Id:</td> 
        <td><input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/></td></tr>
        <tr><td>Employee Name:</td> 
        <td><input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
        <tr><td>Employee Email: </td> 
        <td><input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
        <tr><td>Employee Contact:</td>
        <td><input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
        <tr><td></td><td><button type="submit" class="btn btn-success">Update</button> </td></tr>
</table>   
</form>  
</body>  
</html>

crud/employee/templates/index.html
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}       
<br>  
    <h3>Enter Details</h3> 
<table cellpadding="10px">  
<tr><td>Employee Id:</td><td>{{ form.eid }} </td></tr> 
<tr><td>Employee Name:</td><td>{{ form.ename }} </td></tr>
<tr><td>Employee Email:</td><td>{{ form.eemail }} </td></tr> 
<tr><td>Employee Contact:</td><td>{{ form.econtact }} </td></tr>
<tr><td></td><td><button>Submit</button> </td></tr>
</table>    
</form>  
</body>  
</html>

crud/employee/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
    {%load static%} 
    <link rel="stylesheet" href="{%static 'css/1.css'%}">
</head>  
<body>  
<table>  
    <thead>  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}">Edit</a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  